<?php
// ── generate_wrapper.php ──────────────────────────────────────────────────────
// Generates and downloads a ready-to-use Invoke-<Key>Remote.ps1 WinRM wrapper
// for any registered process.
//
// GET params:
//   process  (key) — required, must exist in config/processes.php
//
// Usage: visit /generate_wrapper.php?process=myprocess
//        → downloads Invoke-MyprocessRemote.ps1
// ─────────────────────────────────────────────────────────────────────────────

require_once __DIR__ . '/includes/auth.php';
requireAuth();

$config     = require __DIR__ . '/config/app.php';
$processes  = require __DIR__ . '/config/processes.php';
$processKey = trim($_GET['process'] ?? '');

if (empty($processKey) || !isset($processes[$processKey])) {
    http_response_code(400);
    echo 'Unknown process: ' . htmlspecialchars($processKey);
    exit;
}

$proc         = $processes[$processKey];
$remoteServer = $proc['remote_server'] ?? $config['winrm_server'];
$remoteScript = $proc['remote_script'] ?? '';
$fileName     = 'Invoke-' . ucfirst($processKey) . 'Remote.ps1';

// ── Generate wrapper content ──────────────────────────────────────────────────
$content = <<<PS
#Requires -Version 5.1
<#
.SYNOPSIS
    WinRM wrapper for {$proc['name']} — generated by ETL Control Panel.
    Invoked by the web app via Windows Task Scheduler on the web server.
    Connects to {$remoteServer} via WinRM and runs the ETL script.

.PARAMETER ExtraArgs
    Additional arguments forwarded to the ETL script.
    Passed by trigger.php based on whether the user clicked Run or Test.

.NOTES
    Deploy to: {$config['wrapper_root']}\\{$fileName}
    Naming convention: Invoke-<processKey>Remote.ps1

    Register the on-demand task after deploying:
        Register-AllETLTasks.ps1
#>

param(
    [string]\$ExtraArgs = ""
)
\$ErrorActionPreference = "Stop"
\$remoteServer = "{$remoteServer}"
\$remoteScript = "{$remoteScript}"

try {
    Invoke-Command -ComputerName \$remoteServer `
                   -Authentication Negotiate `
                   -ScriptBlock {
                       param(\$script, \$extraArgs)
                       Set-ExecutionPolicy Bypass -Scope Process -Force
                       if (\$extraArgs) {
                           Invoke-Expression "& \`"\$script\`" \$extraArgs"
                       } else {
                           & \$script
                       }
                   } `
                   -ArgumentList \$remoteScript, \$ExtraArgs
} catch {
    throw
}
PS;

// ── Stream as downloadable file ───────────────────────────────────────────────
header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename="' . $fileName . '"');
header('Content-Length: ' . strlen($content));
header('Cache-Control: no-cache');
echo $content;
